Repository Open-Agriculture/AgIsoStack-plus-plus, pull requests merged in 2022-11, with the labels that each got.

#37 [Core]: Fix a small memory leak in the socket CAN layer
  socket_can/src/socket_can_interface.cpp
Labels: bug

#40 [39] Add support for ctest to enable/disable testing
  CMakeLists.txt
  README.md
Labels: documentation, enhancement

#45 [Core]: Fix compilation on Alpine Linux
  socket_can/src/socket_can_interface.cpp
Labels: bug

#47 [Meta]: Fix submodule instructions in tutorial
  README.md
  sphinx/source/Installation.rst
Labels: documentation

#51 [Core]: Fix unneeded includes in CAN Hardware Interface
  hardware_integration/src/can_hardware_interface.cpp
Labels: bug

#53 [Core]: Change all std::to_string calls to use a workaround
  isobus/src/can_extended_transport_protocol.cpp
  isobus/src/can_network_manager.cpp
  isobus/src/can_parameter_group_number_request_protocol.cpp
  isobus/src/can_transport_protocol.cpp
  isobus/src/isobus_virtual_terminal_client.cpp
  utility/CMakeLists.txt
  utility/include/to_string.hpp
Labels: enhancement

#50 [Meta]: Added a gitlab-ci file
  .gitlab-ci.yml
Labels: ci/build system
