Repository Open-Agriculture/AgIsoStack-plus-plus, pull requests merged in 2023-06, with the labels that each got.

#272 [Examples]: Fix missing linkage to Threads::Threads in guidance example
  examples/guidance/CMakeLists.txt
Labels: bug

#280 [VT] Graceful shutdown/restart, improvements to some object pool uploads
  isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp
  isobus/src/isobus_virtual_terminal_client.cpp
Labels: bug, enhancement

#275 [VT/TC]: Add country code to language command interface
  isobus/include/isobus/isobus/isobus_language_command_interface.hpp
  isobus/src/isobus_language_command_interface.cpp
  test/language_command_interface_tests.cpp
Labels: enhancement

#283 [Core]: Differentiate rvalues/lvalues in EventDispatcher
  isobus/src/isobus_guidance_interface.cpp
  isobus/src/isobus_maintain_power_interface.cpp
  isobus/src/isobus_shortcut_button_interface.cpp
  isobus/src/isobus_speed_distance_messages.cpp
  test/event_dispatcher_tests.cpp
  utility/include/isobus/utility/event_dispatcher.hpp
Labels: enhancement
