Repository Open-Agriculture/AgIsoStack-plus-plus, pull requests merged in 2023-01, with the labels that each got.

#103 [#102]: Change how partner and ICF list maintenance is done when members are deleted
  CMakeLists.txt
  isobus/src/can_internal_control_function.cpp
  isobus/src/can_network_manager.cpp
  isobus/src/can_partnered_control_function.cpp
  test/core_network_management_tests.cpp
Labels: bug

#106 [Core]: Change internal control function list to be a vector
  isobus/include/isobus/isobus/can_internal_control_function.hpp
  isobus/include/isobus/isobus/can_network_manager.hpp
  isobus/src/can_internal_control_function.cpp
Labels: bug

#99 [Core]: Added a way to register for a PGN callback for any CF
  isobus/include/isobus/isobus/can_network_manager.hpp
  isobus/src/can_network_manager.cpp
Labels: enhancement

#109 [#108]: Update sphinx tutorial docs
  sphinx/source/Tutorials/Adding a Destination.rst
  sphinx/source/Tutorials/Receiving Messages.rst
  sphinx/source/Tutorials/The ISOBUS Hello World.rst
  sphinx/source/Tutorials/Virtual Terminal Basics.rst
Labels: documentation

#105 [#92]: Add Fast Packet documetation to the sphinx docs
  sphinx/source/Concepts.rst
  sphinx/source/Tutorials/Transport Layer.rst
Labels: documentation

#110 [#101]: Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#115 [VT]: Minor VT code quality fixes
  isobus/src/isobus_virtual_terminal_client.cpp
Labels: bug

#117 [#114]: Always process VT NACKs
  isobus/src/isobus_virtual_terminal_client.cpp
Labels: bug

#118 [VT]: Automatically clean up old versions of object pools
  isobus/src/isobus_virtual_terminal_client.cpp
Labels: enhancement

#122 [ETP]: Fix ETP Rx message contents not matching the expected content
  isobus/src/can_extended_transport_protocol.cpp
Labels: bug

#127 [#125]: Add processing of user supplied data chunk callbacks for VT uploads
  isobus/src/isobus_virtual_terminal_client.cpp
Labels: bug

#141 [ETP]: Fix a crash in ETP when aborting while in a TxDataSession state
  isobus/src/can_extended_transport_protocol.cpp
Labels: bug

#140 [VT]: Fix accessing a u24 as a u32 when parsing VT NACK
  isobus/include/isobus/isobus/can_message.hpp
  isobus/src/can_message.cpp
  isobus/src/isobus_virtual_terminal_client.cpp
Labels: bug

#147 [Meta]: Change CI build to compile the example programs
  .github/workflows/cmake.yml
Labels: ci/build system

#156 [Meta]: Add missing tests directory parameter
  CMakeLists.txt
  sonar-project.properties
Labels: ci/build system
