Repository Open-Agriculture/AgIsoStack-plus-plus, pull requests merged in 2023-11, with the labels that each got.

#348 [Meta/Examples]: Update all example manufacturer codes to 1407 (Open-Agriculture)
  README.md
  examples/diagnostic_protocol/main.cpp
  examples/guidance/main.cpp
  examples/nmea2000/fast_packet_protocol/main.cpp
  examples/nmea2000/nmea2000_generator/main.cpp
  examples/nmea2000/nmea2000_parser/main.cpp
  examples/pgn_requests/main.cpp
  examples/task_controller_client/main.cpp
  examples/transport_layer/main.cpp
  examples/virtual_terminal/aux_functions/main.cpp
  examples/virtual_terminal/aux_inputs/main.cpp
  examples/virtual_terminal/esp32_platformio_object_pool/src/main.cpp
  examples/virtual_terminal/version3_object_pool/main.cpp
  sphinx/source/Tutorials/Adding a Destination.rst
  sphinx/source/Tutorials/ESP32 PlatformIO.rst
  sphinx/source/Tutorials/Receiving Messages.rst
  sphinx/source/Tutorials/The ISOBUS Hello World.rst
  sphinx/source/Tutorials/Virtual Terminal Basics.rst
  test/core_network_management_tests.cpp
  test/diagnostic_protocol_tests.cpp
  test/guidance_tests.cpp
  test/language_command_interface_tests.cpp
  test/maintain_power_tests.cpp
  test/nmea2000_message_tests.cpp
  test/speed_distance_message_tests.cpp
  test/vt_client_tests.cpp
Labels: documentation

#356 [CI/Meta]: Add documentation validation checking
  .github/workflows/linting.yml
  doxyfile
  hardware_integration/include/isobus/hardware_integration/can_hardware_interface.hpp
  hardware_integration/include/isobus/hardware_integration/can_hardware_interface_single_thread.hpp
  hardware_integration/include/isobus/hardware_integration/can_hardware_plugin.hpp
  hardware_integration/include/isobus/hardware_integration/flex_can_t4_plugin.hpp
  hardware_integration/include/isobus/hardware_integration/mcp2515_can_interface.hpp
  hardware_integration/src/can_hardware_interface.cpp
  hardware_integration/src/can_hardware_interface_single_thread.cpp
  isobus/include/isobus/isobus/can_NAME_filter.hpp
  isobus/include/isobus/isobus/can_address_claim_state_machine.hpp
  isobus/include/isobus/isobus/can_callbacks.hpp
  isobus/include/isobus/isobus/can_control_function.hpp
  isobus/include/isobus/isobus/can_extended_transport_protocol.hpp
  isobus/include/isobus/isobus/can_hardware_abstraction.hpp
  isobus/include/isobus/isobus/can_identifier.hpp
  isobus/include/isobus/isobus/can_internal_control_function.hpp
  isobus/include/isobus/isobus/can_network_manager.hpp
  isobus/include/isobus/isobus/can_partnered_control_function.hpp
  isobus/include/isobus/isobus/can_transport_protocol.hpp
  isobus/include/isobus/isobus/isobus_device_descriptor_object_pool.hpp
  isobus/include/isobus/isobus/isobus_diagnostic_protocol.hpp
  isobus/include/isobus/isobus/isobus_functionalities.hpp
  isobus/include/isobus/isobus/isobus_guidance_interface.hpp
  isobus/include/isobus/isobus/isobus_language_command_interface.hpp
  isobus/include/isobus/isobus/isobus_maintain_power_interface.hpp
  isobus/include/isobus/isobus/isobus_speed_distance_messages.hpp
  isobus/include/isobus/isobus/isobus_task_controller_client.hpp
  isobus/include/isobus/isobus/isobus_task_controller_client_objects.hpp
  isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp
  isobus/include/isobus/isobus/nmea2000_fast_packet_protocol.hpp
  isobus/include/isobus/isobus/nmea2000_message_definitions.hpp
  isobus/include/isobus/isobus/nmea2000_message_interface.hpp
  isobus/src/nmea2000_fast_packet_protocol.cpp
Labels: documentation, ci/build system

#361 Add missing <string> include in NMEA2000 interface
  isobus/include/isobus/isobus/nmea2000_message_definitions.hpp
Labels: bug, os: linux
