Repository Open-Agriculture/AgIsoStack-plus-plus, pull requests merged in 2023-02, with the labels that each got.

#176 [#175]: Run analysis on external contributions
  .github/workflows/build.yml
  .github/workflows/cmake.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/sonar.yml
Labels: ci/build system

#172 [#170] Standardize "color" to "colour"
  isobus/include/isobus/isobus/isobus_virtual_terminal_client.hpp
  isobus/src/isobus_virtual_terminal_client.cpp
Labels: documentation

#169 [Examples]: Change `_exit` to `_Exit`
  examples/diagnostic_protocol/main.cpp
  examples/nmea2000/main.cpp
  examples/pgn_requests/main.cpp
  examples/transport_layer/main.cpp
  examples/vt_aux_n/main.cpp
  examples/vt_version_3_object_pool/main.cpp
Labels: bug

#179 [DP]: Fix diagnostic protocol create/destroy bugs
  CMakeLists.txt
  isobus/src/isobus_diagnostic_protocol.cpp
  test/diagnostic_protocol_tests.cpp
Labels: bug

#181 [CI] Make sonar-scanner aware of pull request key, branch, base and repo
  .github/workflows/build.yml
Labels: ci/build system

#183 [Core]: Fix a crash that can occur if a hardware channel is nullptr
  hardware_integration/src/can_hardware_interface.cpp
Labels: bug

#184 [Core]: Added remaining ISO Function Codes
  isobus/include/isobus/isobus/can_NAME.hpp
Labels: enhancement

#187 [TC]: Add some standard DDI definitions
  isobus/CMakeLists.txt
  isobus/include/isobus/isobus/isobus_standard_data_description_indices.hpp
Labels: enhancement

#190 [Meta]: Welcome contributions and add code coverage requirement
  CONTRIBUTING.md
Labels: documentation

#191 [Core]: Add MacOS support for the Peak PCAN drivers through the MacCAN driver
  CMakeLists.txt
  README.md
  doxyfile
  examples/diagnostic_protocol/main.cpp
  examples/nmea2000/main.cpp
  examples/pgn_requests/main.cpp
  examples/transport_layer/main.cpp
  examples/vt_aux_n/main.cpp
  examples/vt_version_3_object_pool/main.cpp
  hardware_integration/CMakeLists.txt
  hardware_integration/include/isobus/hardware_integration/PCBUSB.h
  hardware_integration/include/isobus/hardware_integration/available_can_drivers.hpp
  hardware_integration/include/isobus/hardware_integration/mac_can_pcan_plugin.hpp
  hardware_integration/lib/Mac/libPCBUSB.0.12.dylib
  hardware_integration/src/mac_can_pcan_plugin.cpp
  isobus/include/isobus/isobus/can_message.hpp
  isobus/src/isobus_virtual_terminal_client.cpp
  sonar-project.properties
Labels: enhancement
