Repository Open-Agriculture/AgIsoStack-plus-plus, pull requests merged in 2023-10, with the labels that each got.

#331 [CI]: remove approve step and upgrade sonar
  .github/workflows/build.yml
Labels: ci/build system

#333 Switch to debug builds in CI to catch asserts in unit tests
  .github/workflows/build.yml
Labels: ci/build system

#334 [ETP]: Fixed an issue where receiving some ETP sessions could cause a crash
  isobus/src/can_extended_transport_protocol.cpp
Labels: bug

#337 [VT]: Fixed issues uploading multiple object pool chunks to a VT
  isobus/src/isobus_virtual_terminal_client.cpp
Labels: bug

#340 [Meta]: Modernized setting the C++ version in CMake
  CMakeLists.txt
  examples/diagnostic_protocol/CMakeLists.txt
  examples/guidance/CMakeLists.txt
  examples/nmea2000/CMakeLists.txt
  examples/pgn_requests/CMakeLists.txt
  examples/task_controller_client/CMakeLists.txt
  examples/transport_layer/CMakeLists.txt
  examples/virtual_terminal/aux_functions/CMakeLists.txt
  examples/virtual_terminal/aux_inputs/CMakeLists.txt
  examples/virtual_terminal/version3_object_pool/CMakeLists.txt
  hardware_integration/CMakeLists.txt
  isobus/CMakeLists.txt
  utility/CMakeLists.txt
Labels: enhancement

#341 [Meta]: Updated some outdated README info
  README.md
Labels: documentation

#342 [VT/TC]: Language Command Sending and Setters
  isobus/include/isobus/isobus/isobus_language_command_interface.hpp
  isobus/src/isobus_language_command_interface.cpp
  test/language_command_interface_tests.cpp
Labels: enhancement
